apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null   #  create a time stamp about pod  (optional)
  labels:
    x: ashupod1
  name: ashupod1   #  name of the pod
spec:
  containers:
  - image: nginx    # image name from docker HUB and nginx is a webserver 
    name: ashupod1    #  container name 
    ports:
     - containerPort: 80     #  this port will be very much same as Expose in dockerfile
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
